# Generated by Django 3.0.2 on 2020-01-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gpsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sx', models.CharField(max_length=50)),
                ('sy', models.CharField(max_length=50)),
                ('ex', models.CharField(max_length=50)),
                ('ey', models.CharField(max_length=50)),
                ('opt', models.CharField(max_length=50)),
                ('SearchType', models.CharField(max_length=50)),
                ('SearchPathType', models.CharField(max_length=50)),
            ],
        ),
    ]
