# Generated by Django 3.0.2 on 2020-01-16 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('odsay_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpsdata',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
